#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$commands = (new App\Console\Kernel)->getCommands();

$app = new Application();

if(is_array($commands)){
    foreach ($commands as $command) {
        $app->add(new $command);
    }
}

$app->run();
